# Generated by Django 2.2.4 on 2019-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_kz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('poster', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('premiere', models.DateField(blank=True)),
                ('duration', models.PositiveIntegerField(null=True)),
                ('age', models.PositiveIntegerField(default=18)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
    ]
