# Generated by Django 2.2.4 on 2019-08-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_kz', '0003_auto_20190818_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoonMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('premiere', models.DateField(blank=True)),
                ('description', models.TextField(null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('poster', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
