# Generated by Django 2.2.4 on 2019-08-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_kz', '0005_auto_20190818_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
