# Generated by Django 2.2.4 on 2019-08-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino_kz', '0006_cinema_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='city',
        ),
    ]
