# Generated by Django 2.2.4 on 2019-08-28 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_kz', '0007_remove_cinema_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 28, 12, 47, 27, 836099)),
        ),
    ]
