# Generated by Django 2.2.4 on 2019-08-30 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino_kz', '0008_auto_20190828_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 30, 19, 55, 46, 608470)),
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kino_kz.City'),
        ),
    ]
