# Generated by Django 2.2.4 on 2019-08-30 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_kz', '0009_auto_20190830_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 30, 19, 56, 23, 952380)),
        ),
    ]
